#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"

include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~EOS
      Usage:
        kbsecret rm-session [options] <session>
    EOS

    o.bool "-d", "--delete", "unlink the session in addition to deconfiguration"
  end

  c.dreck do
    string :session
  end

  c.ensure_session! :argument
end

label = cmd.args[:session]

cmd.session.unlink! if cmd.opts.delete?

Config.deconfigure_session label
