#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"

include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret sessions [options]
    HELP

    o.bool "-a", "--show-all", "show each session in depth (i.e. metadata)"
  end
end

Config.session_labels.each do |sess_name|
  session_hash = Config.session(sess_name)
  session      = cmd.guard { Session[sess_name] }

  puts sess_name

  next unless cmd.opts.show_all?

  if session_hash[:team]
    puts <<~DETAIL
      \tTeam: #{session_hash[:team]}
      \tSecrets root: #{session_hash[:root]} (#{session.path})
    DETAIL
  else
    puts <<~DETAIL
      \tUsers: #{session_hash[:users].join(", ")}
      \tSecrets root: #{session_hash[:root]} (#{session.path})
    DETAIL
  end
end
