#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"

include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~EOS
      Usage:
        kbsecret dump-fields [options] <record>
    EOS

    o.string "-s", "--session", "the session to search in", default: :default
    o.bool "-x", "--terse", "output in field<sep>value format"
    o.string "-i", "--ifs", "separate terse pairs with this string", default: CLI.ifs
  end

  c.dreck do
    string :label
  end

  c.ensure_session!
end

label   = cmd.args[:label]
record  = cmd.session[label]

cmd.die "No such record." unless record

field_values = record.data_fields.map { |f| record.send f }
field_pairs  = record.data_fields.zip(field_values)

if cmd.opts.terse?
  puts field_pairs.map { |f, v| "#{f}#{cmd.opts[:ifs]}#{v}" }.join "\n"
else
  puts field_pairs.map { |f, v| "#{f}: #{v}" }.join "\n"
end
