#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"
require "clipboard"

include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret pass [options] <record>
    HELP

    o.string "-s", "--session", "the session to search in", default: :default
    o.bool "-c", "--clipboard", "dump the password in the clipboard"
  end

  c.dreck do
    string :label
  end

  c.ensure_session!
end

label   = cmd.args[:label]
record  = cmd.session[label]

cmd.die "No such record." unless record
cmd.die "'#{record}' is not a login record." unless record.type == :login

if cmd.opts.clipboard?
  Clipboard.copy record.password
else
  puts record.password
end
