#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"

include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret env [options] <record [record ...]>
    HELP

    o.string "-s", "--session", "the session to search in", default: :default
    o.bool "-a", "--all", "retrieve all environment records, not just listed ones"
    o.bool "-v", "--value-only", "print only the environment value, not the key"
    o.bool "-p", "--pairs", "print only VAR=val keypairs without `export`"
  end

  unless c.opts.all?
    c.dreck do
      list :string, :labels
    end
  end

  c.ensure_session!
end

records = cmd.session.records :environment

selected_records = if cmd.opts.all?
                     records
                   else
                     records.select do |record|
                       cmd.args[:labels].include? record.label
                     end
                   end

selected_records.each do |record|
  if cmd.opts.value_only?
    puts record.value
  elsif cmd.opts.pairs?
    puts record.to_assignment
  else
    puts record.to_export
  end
end
