#!/usr/bin/env ruby
# frozen_string_literal: true

require "keybase"
require "kbsecret"

include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~EOS
      Usage:
        kbsecret new-session [options] --label <label> --root <dir>
    EOS

    o.string "-l", "--label", "the session label"
    o.array "-u", "--users", "the keybase users", default: [Keybase.current_user]
    o.string "-r", "--root", "the secret root directory"
    o.bool "-f", "--force", "force creation (ignore overwrites, etc.)"
    o.bool "-n", "--no-notify", "do not send a notification to session members"
  end
end

cmd.opts[:users].each do |user|
  cmd.die "Nonexistent Keybase user: '#{user}'" unless Keybase::API.user? user
end

unless cmd.opts[:users].include? Keybase.current_user
  cmd.warn "You didn't include yourself in the user list, but I'll add you."
  cmd.opts[:users] << Keybase.current_user
end

session_label = cmd.opts[:label]

if Config.session?(session_label) && !cmd.opts.force?
  cmd.die "Refusing to overwrite an existing session without --force."
end

Config.configure_session(session_label, users: cmd.opts[:users], root: cmd.opts[:root])

unless cmd.opts.no_notify? && cmd.opts[:users] != [Keybase.current_user]
  users = cmd.opts[:users].join(",")

  Keybase::Chat.send_message cmd.opts[:users], <<~EOM
    You've been added to a KBSecret session!

    To access this session, please run the following:

    ```
      $ kbsecret new-session -l '<your label>' -r '#{cmd.opts[:root]}' -u #{users}
    ```

    If you don't have KBSecret installed, you can install it from `gem`:

    ```
      $ gem install kbsecret
    ```
  EOM
end
