#!/usr/bin/env ruby
# frozen_string_literal: true

require "keybase"
require "kbsecret"

include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret new-session [options]
    HELP

    o.string "-t", "--team", "the team to create the session under"
    o.string "-l", "--label", "the session label", required: true
    o.array "-u", "--users", "the keybase users", default: [Keybase::Local.current_user]
    o.string "-r", "--root", "the secret root directory"
    o.bool "-f", "--force", "force creation (ignore overwrites, etc.)"
    o.bool "-n", "--no-notify", "do not send a notification to session members"
  end
end

session_label = cmd.opts[:label]

if Config.session?(session_label) && !cmd.opts.force?
  cmd.die "Refusing to overwrite an existing session without --force."
end

if cmd.opts[:team]
  teams = Keybase::Local::Team.list_memberships["teams"]

  unless teams.any? { |t| t["fq_name"] == cmd.opts[:team] }
    cmd.die "No such team (either nonexistent or non-member)."
  end

  Config.configure_session(session_label, team: cmd.opts[:team], root: session_label)
else
  cmd.opts[:users].each do |user|
    cmd.die "Nonexistent Keybase user: '#{user}'." unless Keybase::API.user? user
  end

  unless cmd.opts[:users].include? Keybase::Local.current_user
    cmd.warn "You didn't include yourself in the user list, but I'll add you."
    cmd.opts[:users] << Keybase::Local.current_user
  end

  Config.configure_session(session_label, users: cmd.opts[:users], root: cmd.opts[:root])

  unless cmd.opts.no_notify? && cmd.opts[:users] != [Keybase::Local.current_user]
    users = cmd.opts[:users].join(",")

    Keybase::Local::Chat.send_message cmd.opts[:users], <<~MESSAGE
      You've been added to a KBSecret session!

      To access this session, please run the following:

      ```
        $ kbsecret new-session -l '<your label>' -r '#{cmd.opts[:root]}' -u #{users}
      ```

      If you don't have KBSecret installed, you can install it from `gem`:

      ```
        $ gem install kbsecret
      ```
    MESSAGE
  end
end
