#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"

include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~EOS
      Usage:
        kbsecret raw-edit [options] <record>
    EOS

    o.string "-s", "--session", "the session to search in", default: :default
  end

  c.dreck do
    string :label
  end

  c.ensure_session!
end

label   = cmd.args[:label]
record  = cmd.session[label]

cmd.die "No such record." unless record

Process.spawn("#{ENV["EDITOR"]} #{record.path}")
record.sync! # just to bump the timestamp
