#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"

include KBSecret

def new_session(label, cmd)
  if Config.session?(label) && !cmd.opts.force?
    cmd.die "Refusing to overwrite an existing session without --force."
  end

  if cmd.opts[:team]
    teams = Keybase::Local::Team.list_self_memberships.teams

    unless teams.any? { |t| t.fq_name == cmd.opts[:team] }
      cmd.die "No such team (either nonexistent or non-member)."
    end

    Config.configure_session(label, team: cmd.opts[:team], root: label)
  else
    cmd.die "Missing `-r', `--root' option." unless cmd.opts[:root]

    cmd.opts[:users].each do |user|
      cmd.die "Nonexistent Keybase user: '#{user}'." unless Keybase::API.user? user
    end

    unless cmd.opts[:users].include? Keybase::Local.current_user
      cmd.warn "You didn't include yourself in the user list, but I'll add you."
      cmd.opts[:users] << Keybase::Local.current_user
    end

    Config.configure_session(label, users: cmd.opts[:users], root: cmd.opts[:root])

    unless cmd.opts.no_notify? && cmd.opts[:users] != [Keybase::Local.current_user]
      users = cmd.opts[:users].join(",")

      Keybase::Local::Chat.send_message cmd.opts[:users], <<~MESSAGE
        You've been added to a KBSecret session!

        To access this session, please run the following:

        ```
          $ kbsecret new-session -r '#{cmd.opts[:root]}' -u #{users} <label>
        ```

        If you don't have KBSecret installed, you can install it from `gem`:

        ```
          $ gem install kbsecret
        ```
      MESSAGE
    end
  end
end

def rm_session(label, cmd)
  cmd.session.unlink! if cmd.opts.delete?
  Config.deconfigure_session label
end

cmd = CLI.create do |c|
  c.slop cmds: %w[new rm] do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret session [options] <new|rm> <label>
    HELP

    o.string "-t", "--team", "the team to create the session under"
    o.array "-u", "--users", "the keybase users", default: [Keybase::Local.current_user]
    o.string "-r", "--root", "the secret root directory"
    o.bool "-f", "--force", "force creation (ignore overwrites, etc.)"
    o.bool "-n", "--no-notify", "do not send a notification to session members"
    o.bool "-d", "--delete", "unlink the session in addition to deconfiguration"
  end

  c.dreck do
    string :command
    string :session
  end

  c.ensure_session! :argument if c.args[:command] == "rm"
end

session_label = cmd.args[:session]

case cmd.args[:command]
when "new"
  new_session session_label, cmd
when "rm"
  rm_session session_label, cmd
else
  cmd.die "Unknown subcommand: '#{cmd.args[:command]}'."
end
