#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"

include KBSecret

cmd = CLI.create do |c|
  c.slop cmds: %w[new rm] do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret generator [options] <new|rm> <generator>
    HELP

    o.string "-F", "--format", "the format of the secrets generated", default: "hex"
    o.integer "-l", "--length", "the length, in bytes, of the secrets generated",
              default: 16
    o.bool "-f", "--force", "force generator creation (ignore overwrite)"
  end

  c.dreck do
    string :command
    string :generator
  end

  c.ensure_generator! :argument if c.args[:command] == "rm"
end

case cmd.args[:command]
when "new"
  if Config.generator?(cmd.args[:generator]) && !cmd.opts.force?
    cmd.die "Refusing to overwrite an existing generator without --force."
  end

  Config.configure_generator(cmd.args[:generator],
                             format: cmd.opts[:format],
                             length: cmd.opts[:length])
when "rm"
  Config.deconfigure_generator(cmd.args[:generator])
else
  cmd.die "Unknown subcommand: '#{cmd.args[:command]}'."
end
