#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"
require "base64"

include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret stash-file <record> [file]
    HELP

    o.string "-s", "--session", "the session to add to", default: :default
    o.bool "-f", "--force", "force creation (ignore overwrites, etc.)"
    o.bool "-b", "--base64", "encode the file as base64"
  end

  c.dreck errors: false do
    string :label
    string :filename
  end

  c.ensure_session!
end

label    = cmd.args[:label]
filename = cmd.args[:filename]

cmd.die "Missing a record label to create." unless label

if cmd.session.record?(label) && !cmd.opts.force?
  cmd.die "Refusing to overwrite an existing record without --force."
end

contents = if filename.empty? || filename == "-"
             STDIN.read
           elsif File.file?(filename)
             File.read(filename)
           else
             cmd.die "That file doesn't exist."
           end

contents = Base64.encode64(contents) if cmd.opts.base64?

cmd.guard { cmd.session.add_record(:unstructured, label, contents) }
