#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"
require "tty-prompt"

include KBSecret

$VERBOSE = nil # tty-prompt blasts us with irrelevant warnings on 2.4

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret rm [options] <record [records ...]>
    HELP

    o.string "-s", "--session", "the session containing the record", default: :default
    o.bool "-i", "--interactive", "ask for confirmation before deleting"
  end

  c.dreck do
    list :string, :labels
  end

  c.ensure_session!
end

records = cmd.session.records :login

selected_records = records.select do |record|
  cmd.args[:labels].include? record.label
end

cmd.die "Can't delete a nonexistent record." unless selected_records

tty = TTY::Prompt.new

confirm = if cmd.opts.interactive?
            tty.yes?("Delete '#{selected_records.join(",")}' from the #{cmd.session.label} session?")
          else true
          end

cmd.session.delete_records(selected_records) if confirm
