#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"

include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret list [options]
    HELP

    o.string "-s", "--session", "the session to list from", default: :default
    o.string "-t", "--type", "the type of secrets to list", default: nil
    o.bool "-a", "--show-all", "show everything in each secret (i.e. metadata)"
  end

  c.ensure_type! if c.opts[:type]
  c.ensure_session!
end

records = cmd.session.records cmd.opts[:type]

records.each do |record|
  puts record.label

  next unless cmd.opts.show_all?

  puts <<~DETAIL
    \tType: #{record.type}
    \tLast changed: #{Time.at(record.timestamp)}
    \tRaw data: #{record.data}
  DETAIL
end
