#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"
include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret cp <src-session> <target-session> [options] <record [record ...]>
    HELP
    o.bool "-m", "--move", "delete the record after copying"
  end

  c.dreck do
    string :session
    string :target_session
    list :string, :labels
  end

  c.ensure_session!(:args)
end

target_session = Session.new(label: cmd.args[:target_session])
cmd.args[:labels].each do |label|
  cmd.die "No such record: #{label}" unless cmd.session.record?(label)
  record = cmd.session[label]
  target_session.import_record(record)
  cmd.session.delete_record(label) if cmd.opts.move?
end
