#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"

include KBSecret

STDERR.puts "This command has been deprecated in favor of 'kbsecret-session'. It will be removed in release 1.0"

exec "kbsecret", "session", "rm", *ARGV
