#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"

include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage:
        kbsecret generators [options]
    HELP

    o.bool "-a", "--show-all", "show each generator in depth (i.e. metadata)"
  end
end

Config[:generators].each do |label, config|
  puts label

  next unless cmd.opts.show_all?

  puts <<~DETAIL
    \tFormat: #{config[:format]}
    \tLength: #{config[:length]}
  DETAIL
end
