#!/usr/bin/env ruby
# frozen_string_literal: true

require "kbsecret"

include KBSecret

cmd = CLI.create do |c|
  c.slop do |o|
    o.banner = <<~HELP
      Usage: kbsecret conf [options]
    HELP

    o.bool "-c", "--commands", "open the commands config (commands.ini)"
    o.bool "-d", "--directory", "print the path to the config directory"
    o.bool "-r", "--record-directory", "print the path to the custom record directory"
  end
end

KBSecret::CLI.die "You need to set $EDITOR!" unless ENV["EDITOR"]

if cmd.opts.commands?
  exec "#{ENV["EDITOR"]} #{Config::COMMAND_CONFIG_FILE}"
elsif cmd.opts.directory?
  puts Config::CONFIG_DIR
elsif cmd.opts.record_directory?
  puts Config::CUSTOM_TYPES_DIR
else
  exec "#{ENV["EDITOR"]} #{Config::CONFIG_FILE}"
end
